analyzer:
  exclude:
    - build/**
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "lib/generated/**"
  errors:
    constant_identifier_names: ignore
    invalid_annotation_target: ignore
    unnecessary_overrides: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - unawaited_futures
