name: huroof
description: "An interactive Arabic language learning app focused on pronunciation."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # --- UI & Animation ---
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  skeletonizer: ^1.4.3
  flutter_spinkit: ^5.2.1
  smooth_page_indicator: ^1.2.1
  step_progress_indicator: ^1.0.2
  avatar_glow: ^3.0.1
  # --- Media & Files ---
  mime: ^2.0.0
  path_provider: ^2.1.5
  audio_waveforms: ^1.3.0
  # --- Networking & APIs ---
  dio: ^5.8.0+1
  http: ^1.3.0
  pretty_dio_logger: ^1.4.0
  flutter_dotenv: ^5.2.1
  # --- Localization & Internationalization ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # --- State Management & Navigation ---
  get: ^4.7.2
  # --- Utility & Core Tools ---
  logger: ^2.5.0
  permission_handler: ^12.0.1
  uuid: ^4.5.1
  # --- Code Generation (Annotations Only) ---
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  # --- Responsive Layout ---
  flutter_screenutil: ^5.9.3
  # --- Storage ---
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.2
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svgs/
    - assets/lottie/
    - assets/translations/
    - assets/data/
    - assets/audio/
    - .env
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri/Amiri-Italic.ttf
          style: italic
        - asset: assets/fonts/Amiri/Amiri-BoldItalic.ttf
          weight: 700
          style: italic
