class ImagePaths {
  const ImagePaths._();
  static const List<String> all = [
    'assets/images/app_icon.png',
    'assets/images/empty_image.png',
    'assets/images/makhraj/ain.jpg',
    'assets/images/makhraj/alif.jpg',
    'assets/images/makhraj/ba.jpg',
    'assets/images/makhraj/dad.jpg',
    'assets/images/makhraj/dal.jpg',
    'assets/images/makhraj/fa.jpg',
    'assets/images/makhraj/ghain.jpg',
    'assets/images/makhraj/ha.jpg',
    'assets/images/makhraj/ha2.jpg',
    'assets/images/makhraj/jeem.jpg',
    'assets/images/makhraj/kaf.jpg',
    'assets/images/makhraj/kha.jpg',
    'assets/images/makhraj/lam.jpg',
    'assets/images/makhraj/meem.jpg',
    'assets/images/makhraj/noon.jpg',
    'assets/images/makhraj/qaf.jpg',
    'assets/images/makhraj/ra.jpg',
    'assets/images/makhraj/sad.jpg',
    'assets/images/makhraj/seen.jpg',
    'assets/images/makhraj/sheen.jpg',
    'assets/images/makhraj/ta.jpg',
    'assets/images/makhraj/taa.jpg',
    'assets/images/makhraj/tha.jpg',
    'assets/images/makhraj/thal.jpg',
    'assets/images/makhraj/waw.jpg',
    'assets/images/makhraj/ya.jpg',
    'assets/images/makhraj/zaa.jpg',
    'assets/images/makhraj/zay.jpg',
    'assets/images/splash.png',
  ];
}
